"""added UnleashedGUID column in tItems table

Revision ID: 17b5515f26bc
Revises: 1931e38e2579
Create Date: 2026-03-08 08:55:52.368338

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '17b5515f26bc'
down_revision = '1931e38e2579'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tItems', sa.Column('UnleashedGUID', sa.Unicode(length=36, collation='Latin1_General_CI_AS'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tItems', 'UnleashedGUID')
    # ### end Alembic commands ###
