"""checkingdb

Revision ID: 1931e38e2579
Revises: 96532b1ceabe
Create Date: 2026-03-05 10:56:49.276435

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '1931e38e2579'
down_revision = '96532b1ceabe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
