"""added new flag for salesheader

Revision ID: 21c73a217426
Revises: d42de61a3d42
Create Date: 2026-04-18 18:13:52.479985

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '21c73a217426'
down_revision = 'd42de61a3d42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tREMOTETransHeader', sa.Column('segwayz_internal', sa.Boolean(), server_default=sa.text('(0)'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tREMOTETransHeader', 'segwayz_internal')
    # ### end Alembic commands ###
