"""tcustomer updated

Revision ID: 5173500b2587
Revises: 1931e38e2579
Create Date: 2026-03-06 19:47:52.414298

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '5173500b2587'
down_revision = '1931e38e2579'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tCustomers', sa.Column('CustomerCode', sa.String(length=10, collation='Latin1_General_CI_AS'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tCustomers', 'CustomerCode')
    # ### end Alembic commands ###
