"""identifer

Revision ID: d09b625a0903
Revises: 3e8473a48117
Create Date: 2026-03-08 20:31:56.438799

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision = 'd09b625a0903'
down_revision = '3e8473a48117'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tCustomers_backup')
    op.alter_column('tCustomers', 'IdentifierID',
               existing_type=sa.NVARCHAR(length=26, collation='Latin1_General_CI_AS'),
               type_=sa.Unicode(length=52, collation='Latin1_General_CI_AS'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tCustomers', 'IdentifierID',
               existing_type=sa.Unicode(length=52, collation='Latin1_General_CI_AS'),
               type_=sa.NVARCHAR(length=26, collation='Latin1_General_CI_AS'),
               existing_nullable=False)
    op.create_table('tCustomers_backup',
    sa.Column('CustomerID', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('CardRecordID', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('CardIdentification', sa.NVARCHAR(length=16, collation='Latin1_General_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('Name', sa.VARCHAR(length=255, collation='Latin1_General_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('LastName', sa.VARCHAR(length=255, collation='Latin1_General_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('FirstName', sa.VARCHAR(length=255, collation='Latin1_General_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('IsIndividual', sa.NVARCHAR(length=1, collation='Latin1_General_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('IsInactive', sa.NVARCHAR(length=1, collation='Latin1_General_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('CurrencyID', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('Picture', sa.NVARCHAR(length=255, collation='Latin1_General_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('Notes', sa.NVARCHAR(length=255, collation='Latin1_General_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('Identifiers', sa.NVARCHAR(length=26, collation='Latin1_General_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('IdentifierID', sa.NVARCHAR(length=26, collation='Latin1_General_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('CustomList1ID', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('CustomList2ID', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('CustomList3ID', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('CustomField1', sa.NVARCHAR(length=255, collation='Latin1_General_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('CustomField2', sa.NVARCHAR(length=255, collation='Latin1_General_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('CustomField3', sa.NVARCHAR(length=255, collation='Latin1_General_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('TermsID', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('ABN', sa.NVARCHAR(length=14, collation='Latin1_General_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('ABNBranch', sa.NVARCHAR(length=11, collation='Latin1_General_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('PriceLevelID', sa.NVARCHAR(length=3, collation='Latin1_General_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('TaxIDNumber', sa.NVARCHAR(length=19, collation='Latin1_General_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('TaxCodeID', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('FreightTaxCodeID', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('UseCustomerTaxCode', sa.NVARCHAR(length=1, collation='Latin1_General_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('CreditLimit', sa.FLOAT(precision=53), autoincrement=False, nullable=False),
    sa.Column('VolumeDiscount', sa.FLOAT(precision=53), autoincrement=False, nullable=False),
    sa.Column('CurrentBalance', sa.FLOAT(precision=53), autoincrement=False, nullable=False),
    sa.Column('TotalDeposits', sa.FLOAT(precision=53), autoincrement=False, nullable=False),
    sa.Column('CustomerSince', mssql.SMALLDATETIME(), autoincrement=False, nullable=True),
    sa.Column('LastSaleDate', mssql.SMALLDATETIME(), autoincrement=False, nullable=True),
    sa.Column('LastPaymentDate', mssql.SMALLDATETIME(), autoincrement=False, nullable=True),
    sa.Column('TotalReceivableDays', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('TotalPaidInvoices', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('HighestInvoiceAmount', sa.FLOAT(precision=53), autoincrement=False, nullable=False),
    sa.Column('HighestReceivableAmount', sa.FLOAT(precision=53), autoincrement=False, nullable=False),
    sa.Column('MethodOfPaymentID', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('PaymentCardNumber', sa.NVARCHAR(length=25, collation='Latin1_General_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('PaymentNameOnCard', sa.NVARCHAR(length=50, collation='Latin1_General_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('PaymentExpirationDate', sa.NVARCHAR(length=10, collation='Latin1_General_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('PaymentBSB', sa.VARCHAR(length=11, collation='Latin1_General_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('PaymentBankAccountNumber', sa.VARCHAR(length=20, collation='Latin1_General_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('PaymentBankAccountName', sa.NVARCHAR(length=32, collation='Latin1_General_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('PaymentNotes', sa.NVARCHAR(length=255, collation='Latin1_General_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('HourlyBillingRate', sa.FLOAT(precision=53), autoincrement=False, nullable=False),
    sa.Column('SaleLayoutID', sa.NVARCHAR(length=1, collation='Latin1_General_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('PrintedForm', sa.NVARCHAR(length=34, collation='Latin1_General_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('IncomeAccountID', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('SalespersonID', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('SaleCommentID', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ShippingMethodID', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ChangeControl', sa.CHAR(length=20, collation='Latin1_General_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('GSTIDNumber', sa.VARCHAR(length=20, collation='Latin1_General_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('ReceiptMemo', sa.VARCHAR(length=255, collation='Latin1_General_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('PaymentBankBranch', sa.VARCHAR(length=10, collation='Latin1_General_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('PaymentAddress', sa.VARCHAR(length=30, collation='Latin1_General_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('PaymentZIP', sa.VARCHAR(length=10, collation='Latin1_General_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('PaymentCardVerification', sa.VARCHAR(length=10, collation='Latin1_General_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('ACCNO', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ONHOLD', sa.CHAR(length=1, collation='Latin1_General_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('CustomerCode', sa.VARCHAR(length=10, collation='Latin1_General_CI_AS'), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
