"""increased customer code limit to 16

Revision ID: d42de61a3d42
Revises: d09b625a0903
Create Date: 2026-03-26 18:45:12.178653

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'd42de61a3d42'
down_revision = 'd09b625a0903'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tCustomers', 'CustomerCode',
               existing_type=sa.VARCHAR(length=10, collation='Latin1_General_CI_AS'),
               type_=sa.String(length=16, collation='Latin1_General_CI_AS'),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tCustomers', 'CustomerCode',
               existing_type=sa.String(length=16, collation='Latin1_General_CI_AS'),
               type_=sa.VARCHAR(length=10, collation='Latin1_General_CI_AS'),
               existing_nullable=True)
    # ### end Alembic commands ###
